FROM node:20-alpine

WORKDIR /app

COPY package.json ./
COPY tsconfig.base.json ./
COPY apps/api/package.json ./apps/api/package.json
COPY packages/contracts/package.json ./packages/contracts/package.json

RUN npm install

COPY apps/api ./apps/api
COPY packages/contracts ./packages/contracts

EXPOSE 3333

CMD ["npm", "run", "dev:api"]
