FROM node:20-alpine

WORKDIR /app

COPY package.json ./
COPY tsconfig.base.json ./
COPY apps/web/package.json ./apps/web/package.json
COPY packages/contracts/package.json ./packages/contracts/package.json

RUN npm install

COPY apps/web ./apps/web
COPY packages/contracts ./packages/contracts

EXPOSE 3000

CMD ["npm", "run", "dev:web"]
